/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.preview;

/**
 *
 * @author Jonisan
 */
public class CharacterPanelPreview extends javax.swing.JPanel
{

    /**
     * Creates new form CharacterPanelPreview
     */
    public CharacterPanelPreview()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        forceOrLetRadioGroup = new javax.swing.ButtonGroup();
        bladderRadioGroup = new javax.swing.ButtonGroup();
        incontinenceRadioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        wettingSceneComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        forceParametersRadioButton = new javax.swing.JRadioButton();
        forcedParametersPanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        bladderPanel = new javax.swing.JPanel();
        definedBladderRadioButton = new javax.swing.JRadioButton();
        bladderSpinner = new javax.swing.JSpinner();
        randomBladderRadioButton = new javax.swing.JRadioButton();
        randomBladderFromLabel = new javax.swing.JLabel();
        randomBladderFromSpinner = new javax.swing.JSpinner();
        randomBladderToLabel = new javax.swing.JLabel();
        randomBladderToSpinner = new javax.swing.JSpinner();
        incontinencePanel = new javax.swing.JPanel();
        definedIncontinenceRadioButton = new javax.swing.JRadioButton();
        definedIncontinenceSpinner = new javax.swing.JSpinner();
        randomIncontinenceRadioButton = new javax.swing.JRadioButton();
        randomIncontinenceFromLabel = new javax.swing.JLabel();
        randomIncontinenceFromSpinner = new javax.swing.JSpinner();
        randomIncontinenceToLabel = new javax.swing.JLabel();
        randomIncontinenceToSpinner = new javax.swing.JSpinner();
        underwearSelectLabel = new javax.swing.JLabel();
        underwearSelectButton = new javax.swing.JButton();
        outerwearSelectLabel = new javax.swing.JLabel();
        outerwearSelectButton = new javax.swing.JButton();
        letParametersRadioGroup = new javax.swing.JRadioButton();
        letParametersPanel = new javax.swing.JPanel();
        letBladderPanel = new javax.swing.JPanel();
        letBladderDefinedFromSpinner = new javax.swing.JSpinner();
        letBladderRandomFromLabel = new javax.swing.JLabel();
        letBladderRandomFromSpinner = new javax.swing.JSpinner();
        letBladderRandomToLabel = new javax.swing.JLabel();
        letBladderRandomToSpinner = new javax.swing.JSpinner();
        letBladderDefinedFromLabel = new javax.swing.JLabel();
        definedBladderCheckbox = new javax.swing.JCheckBox();
        letBladderDefinedToLabel = new javax.swing.JLabel();
        letBladderDefinedToSpinner = new javax.swing.JSpinner();
        letBladderRandomCheckbox = new javax.swing.JCheckBox();
        letIncontinencePanel = new javax.swing.JPanel();
        definedIncontinenceCheckbox = new javax.swing.JCheckBox();
        definedIncontinenceFromLabel = new javax.swing.JLabel();
        definedIncontinenceFromSpinner = new javax.swing.JSpinner();
        definedIncontinenceToSpinner = new javax.swing.JSpinner();
        definedIncontinenceToLabel = new javax.swing.JLabel();
        randomIncontinenceCheckbox = new javax.swing.JCheckBox();
        letRandomIncontinenceFromLabel = new javax.swing.JLabel();
        letRandomIncontinenceToLabel = new javax.swing.JLabel();
        letRandomIncontinenceToSpinner = new javax.swing.JSpinner();
        letRandomIncontinenceFromSpinner = new javax.swing.JSpinner();
        letUnderwearSelectLabel = new javax.swing.JLabel();
        letUnderwearSelectButton = new javax.swing.JButton();
        letOuterwearSelectLabel = new javax.swing.JLabel();
        letOuterwearSelectButton = new javax.swing.JButton();

        jLabel1.setText("Wetting scene");

        wettingSceneComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<default>" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Allowed parameters"));

        forceOrLetRadioGroup.add(forceParametersRadioButton);
        forceParametersRadioButton.setText("Force this parameters");

        forcedParametersPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setText("Character name");

        bladderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bladder at start"));

        bladderRadioGroup.add(definedBladderRadioButton);

        bladderSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        bladderRadioGroup.add(randomBladderRadioButton);
        randomBladderRadioButton.setText("Random");

        randomBladderFromLabel.setText("From");

        randomBladderFromSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        randomBladderToLabel.setText("To");

        randomBladderToSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)50), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        javax.swing.GroupLayout bladderPanelLayout = new javax.swing.GroupLayout(bladderPanel);
        bladderPanel.setLayout(bladderPanelLayout);
        bladderPanelLayout.setHorizontalGroup(
            bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bladderPanelLayout.createSequentialGroup()
                .addComponent(definedBladderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bladderSpinner))
            .addGroup(bladderPanelLayout.createSequentialGroup()
                .addComponent(randomBladderRadioButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bladderPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomBladderFromLabel)
                    .addComponent(randomBladderToLabel))
                .addGap(18, 18, 18)
                .addGroup(bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomBladderToSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(randomBladderFromSpinner)))
        );
        bladderPanelLayout.setVerticalGroup(
            bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bladderPanelLayout.createSequentialGroup()
                .addGroup(bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bladderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bladderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(definedBladderRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomBladderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomBladderFromLabel)
                    .addComponent(randomBladderFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomBladderToLabel)
                    .addComponent(randomBladderToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        incontinencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Incontinence"));

        incontinenceRadioGroup.add(definedIncontinenceRadioButton);

        definedIncontinenceSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        incontinenceRadioGroup.add(randomIncontinenceRadioButton);
        randomIncontinenceRadioButton.setText("Random");

        randomIncontinenceFromLabel.setText("From");

        randomIncontinenceFromSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        randomIncontinenceToLabel.setText("To");

        randomIncontinenceToSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        javax.swing.GroupLayout incontinencePanelLayout = new javax.swing.GroupLayout(incontinencePanel);
        incontinencePanel.setLayout(incontinencePanelLayout);
        incontinencePanelLayout.setHorizontalGroup(
            incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incontinencePanelLayout.createSequentialGroup()
                .addComponent(definedIncontinenceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(definedIncontinenceSpinner))
            .addGroup(incontinencePanelLayout.createSequentialGroup()
                .addComponent(randomIncontinenceRadioButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(incontinencePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomIncontinenceFromLabel)
                    .addComponent(randomIncontinenceToLabel))
                .addGap(18, 18, 18)
                .addGroup(incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomIncontinenceToSpinner)
                    .addComponent(randomIncontinenceFromSpinner)))
        );
        incontinencePanelLayout.setVerticalGroup(
            incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incontinencePanelLayout.createSequentialGroup()
                .addGroup(incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(definedIncontinenceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(incontinencePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(definedIncontinenceRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomIncontinenceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomIncontinenceFromLabel)
                    .addComponent(randomIncontinenceFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomIncontinenceToLabel)
                    .addComponent(randomIncontinenceToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        underwearSelectLabel.setText("Underwear");

        underwearSelectButton.setText("Select...");

        outerwearSelectLabel.setText("Outerwear");

        outerwearSelectButton.setText("Select...");

        javax.swing.GroupLayout forcedParametersPanelLayout = new javax.swing.GroupLayout(forcedParametersPanel);
        forcedParametersPanel.setLayout(forcedParametersPanelLayout);
        forcedParametersPanelLayout.setHorizontalGroup(
            forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forcedParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bladderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(forcedParametersPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField))
                    .addComponent(incontinencePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(forcedParametersPanelLayout.createSequentialGroup()
                        .addGroup(forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(underwearSelectLabel)
                            .addComponent(outerwearSelectLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outerwearSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(underwearSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        forcedParametersPanelLayout.setVerticalGroup(
            forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forcedParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bladderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incontinencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(underwearSelectLabel)
                    .addComponent(underwearSelectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forcedParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outerwearSelectButton)
                    .addComponent(outerwearSelectLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        forceOrLetRadioGroup.add(letParametersRadioGroup);
        letParametersRadioGroup.setText("Let player select parameters");

        letParametersPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        letBladderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bladder at start"));

        letBladderDefinedFromSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        letBladderRandomFromLabel.setText("From");

        letBladderRandomFromSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        letBladderRandomToLabel.setText("To");

        letBladderRandomToSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)50), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        letBladderDefinedFromLabel.setText("From");

        definedBladderCheckbox.setSelected(true);
        definedBladderCheckbox.setText("Defined");

        letBladderDefinedToLabel.setText("To");

        letBladderDefinedToSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)130), Short.valueOf((short)0), Short.valueOf((short)130), Short.valueOf((short)1)));

        letBladderRandomCheckbox.setSelected(true);
        letBladderRandomCheckbox.setText("Random");

        javax.swing.GroupLayout letBladderPanelLayout = new javax.swing.GroupLayout(letBladderPanel);
        letBladderPanel.setLayout(letBladderPanelLayout);
        letBladderPanelLayout.setHorizontalGroup(
            letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letBladderPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(letBladderPanelLayout.createSequentialGroup()
                        .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letBladderRandomFromLabel)
                            .addComponent(letBladderRandomToLabel))
                        .addGap(18, 18, 18)
                        .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letBladderRandomToSpinner)
                            .addComponent(letBladderRandomFromSpinner)))
                    .addGroup(letBladderPanelLayout.createSequentialGroup()
                        .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letBladderDefinedFromLabel)
                            .addComponent(letBladderDefinedToLabel))
                        .addGap(18, 18, 18)
                        .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letBladderDefinedToSpinner)
                            .addComponent(letBladderDefinedFromSpinner)))))
            .addGroup(letBladderPanelLayout.createSequentialGroup()
                .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(definedBladderCheckbox)
                    .addComponent(letBladderRandomCheckbox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        letBladderPanelLayout.setVerticalGroup(
            letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letBladderPanelLayout.createSequentialGroup()
                .addComponent(definedBladderCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letBladderDefinedFromLabel)
                    .addComponent(letBladderDefinedFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letBladderDefinedToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letBladderDefinedToLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letBladderRandomCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letBladderRandomFromLabel)
                    .addComponent(letBladderRandomFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letBladderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letBladderRandomToLabel)
                    .addComponent(letBladderRandomToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        letIncontinencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Incontinence"));

        definedIncontinenceCheckbox.setSelected(true);
        definedIncontinenceCheckbox.setText("Defined");

        definedIncontinenceFromLabel.setText("From");

        definedIncontinenceFromSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        definedIncontinenceToSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        definedIncontinenceToLabel.setText("To");

        randomIncontinenceCheckbox.setSelected(true);
        randomIncontinenceCheckbox.setText("Random");

        letRandomIncontinenceFromLabel.setText("From");

        letRandomIncontinenceToLabel.setText("To");

        letRandomIncontinenceToSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        letRandomIncontinenceFromSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.5f), Float.valueOf(10.0f), Float.valueOf(1.0f)));

        javax.swing.GroupLayout letIncontinencePanelLayout = new javax.swing.GroupLayout(letIncontinencePanel);
        letIncontinencePanel.setLayout(letIncontinencePanelLayout);
        letIncontinencePanelLayout.setHorizontalGroup(
            letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letIncontinencePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(definedIncontinenceFromLabel)
                    .addComponent(definedIncontinenceToLabel)
                    .addComponent(letRandomIncontinenceFromLabel)
                    .addComponent(letRandomIncontinenceToLabel))
                .addGap(18, 18, 18)
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(definedIncontinenceToSpinner)
                    .addComponent(definedIncontinenceFromSpinner)
                    .addComponent(letRandomIncontinenceToSpinner)
                    .addComponent(letRandomIncontinenceFromSpinner)))
            .addGroup(letIncontinencePanelLayout.createSequentialGroup()
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(definedIncontinenceCheckbox)
                    .addComponent(randomIncontinenceCheckbox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        letIncontinencePanelLayout.setVerticalGroup(
            letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letIncontinencePanelLayout.createSequentialGroup()
                .addComponent(definedIncontinenceCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definedIncontinenceFromLabel)
                    .addComponent(definedIncontinenceFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definedIncontinenceToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(definedIncontinenceToLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomIncontinenceCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letRandomIncontinenceFromLabel)
                    .addComponent(letRandomIncontinenceFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letIncontinencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letRandomIncontinenceToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letRandomIncontinenceToLabel)))
        );

        letUnderwearSelectLabel.setText("Underwear");

        letUnderwearSelectButton.setText("Select...");

        letOuterwearSelectLabel.setText("Outerwear");

        letOuterwearSelectButton.setText("Select...");

        javax.swing.GroupLayout letParametersPanelLayout = new javax.swing.GroupLayout(letParametersPanel);
        letParametersPanel.setLayout(letParametersPanelLayout);
        letParametersPanelLayout.setHorizontalGroup(
            letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(letBladderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(letIncontinencePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(letParametersPanelLayout.createSequentialGroup()
                        .addGroup(letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letUnderwearSelectLabel)
                            .addComponent(letOuterwearSelectLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letOuterwearSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(letUnderwearSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        letParametersPanelLayout.setVerticalGroup(
            letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(letBladderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letIncontinencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letUnderwearSelectLabel)
                    .addComponent(letUnderwearSelectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letOuterwearSelectButton)
                    .addComponent(letOuterwearSelectLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forceParametersRadioButton)
                    .addComponent(forcedParametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letParametersRadioGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(letParametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(letParametersRadioGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letParametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(forceParametersRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forcedParametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(wettingSceneComboBox, 0, 332, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(wettingSceneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bladderPanel;
    private javax.swing.ButtonGroup bladderRadioGroup;
    private javax.swing.JSpinner bladderSpinner;
    private javax.swing.JCheckBox definedBladderCheckbox;
    private javax.swing.JRadioButton definedBladderRadioButton;
    private javax.swing.JCheckBox definedIncontinenceCheckbox;
    private javax.swing.JLabel definedIncontinenceFromLabel;
    private javax.swing.JSpinner definedIncontinenceFromSpinner;
    private javax.swing.JRadioButton definedIncontinenceRadioButton;
    private javax.swing.JSpinner definedIncontinenceSpinner;
    private javax.swing.JLabel definedIncontinenceToLabel;
    private javax.swing.JSpinner definedIncontinenceToSpinner;
    private javax.swing.ButtonGroup forceOrLetRadioGroup;
    private javax.swing.JRadioButton forceParametersRadioButton;
    private javax.swing.JPanel forcedParametersPanel;
    private javax.swing.JPanel incontinencePanel;
    private javax.swing.ButtonGroup incontinenceRadioGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel letBladderDefinedFromLabel;
    private javax.swing.JSpinner letBladderDefinedFromSpinner;
    private javax.swing.JLabel letBladderDefinedToLabel;
    private javax.swing.JSpinner letBladderDefinedToSpinner;
    private javax.swing.JPanel letBladderPanel;
    private javax.swing.JCheckBox letBladderRandomCheckbox;
    private javax.swing.JLabel letBladderRandomFromLabel;
    private javax.swing.JSpinner letBladderRandomFromSpinner;
    private javax.swing.JLabel letBladderRandomToLabel;
    private javax.swing.JSpinner letBladderRandomToSpinner;
    private javax.swing.JPanel letIncontinencePanel;
    private javax.swing.JButton letOuterwearSelectButton;
    private javax.swing.JLabel letOuterwearSelectLabel;
    private javax.swing.JPanel letParametersPanel;
    private javax.swing.JRadioButton letParametersRadioGroup;
    private javax.swing.JLabel letRandomIncontinenceFromLabel;
    private javax.swing.JSpinner letRandomIncontinenceFromSpinner;
    private javax.swing.JLabel letRandomIncontinenceToLabel;
    private javax.swing.JSpinner letRandomIncontinenceToSpinner;
    private javax.swing.JButton letUnderwearSelectButton;
    private javax.swing.JLabel letUnderwearSelectLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton outerwearSelectButton;
    private javax.swing.JLabel outerwearSelectLabel;
    private javax.swing.JLabel randomBladderFromLabel;
    private javax.swing.JSpinner randomBladderFromSpinner;
    private javax.swing.JRadioButton randomBladderRadioButton;
    private javax.swing.JLabel randomBladderToLabel;
    private javax.swing.JSpinner randomBladderToSpinner;
    private javax.swing.JCheckBox randomIncontinenceCheckbox;
    private javax.swing.JLabel randomIncontinenceFromLabel;
    private javax.swing.JSpinner randomIncontinenceFromSpinner;
    private javax.swing.JRadioButton randomIncontinenceRadioButton;
    private javax.swing.JLabel randomIncontinenceToLabel;
    private javax.swing.JSpinner randomIncontinenceToSpinner;
    private javax.swing.JButton underwearSelectButton;
    private javax.swing.JLabel underwearSelectLabel;
    private javax.swing.JComboBox<String> wettingSceneComboBox;
    // End of variables declaration//GEN-END:variables
}
